Layout/EmptyLinesAroundAttributeAccessor:
  Enabled: false

Layout/SpaceAroundMethodCallOperator:
  Enabled: false

Lint/DeprecatedOpenSSLConstant:
  Enabled: false

Lint/DuplicateElsifCondition:
  Enabled: false

Lint/MixedRegexpCaptureTypes:
  Enabled: false

Lint/RaiseException:
  Enabled: false

Lint/StructNewOverride:
  Enabled: false

Style/AccessorGrouping:
  Enabled: false

Style/ArrayCoercion:
  Enabled: false

Style/BisectedAttrAccessor:
  Enabled: false

Style/CaseLikeIf:
  Enabled: false

Style/ExponentialNotation:
  Enabled: false

Style/HashAsLastArrayItem:
  Enabled: false

Style/HashEachMethods:
  Enabled: false

Style/HashLikeCase:
  Enabled: false

Style/HashTransformKeys:
  Enabled: false

Style/HashTransformValues:
  Enabled: false

Style/RedundantAssignment:
  Enabled: false

Style/RedundantFetchBlock:
  Enabled: false

Style/RedundantFileExtensionInRequire:
  Enabled: false

Style/RedundantRegexpCharacterClass:
  Enabled: false

Style/RedundantRegexpEscape:
  Enabled: false

Style/SlicingWithRange:
  Enabled: false

Rails/ActiveRecordCallbacksOrder:
  Enabled: false

Rails/FindById:
  Enabled: false

Rails/Inquiry:
  Enabled: false

Rails/MailerName:
  Enabled: false

Rails/MatchRoute:
  Enabled: false

Rails/NegateInclude:
  Enabled: false

Rails/Pluck:
  Enabled: false

Rails/PluckInWhere:
  Enabled: false

Rails/RenderInline:
  Enabled: false

Rails/RenderPlainText:
  Enabled: false

Rails/ShortI18n:
  Enabled: false

Rails/WhereExists:
  Enabled: false

Performance/AncestorsInclude:
  Enabled: false

Performance/BigDecimalWithNumericArgument:
  Enabled: false

Performance/RedundantSortBlock:
  Enabled: false

Performance/RedundantStringChars:
  Enabled: false

Performance/ReverseFirst:
  Enabled: false

Performance/SortReverse:
  Enabled: false

Performance/Squeeze:
  Enabled: false

Performance/StringInclude:
  Enabled: false

Rails/RedundantForeignKey:
  Enabled: false

Rails/IndexWith:
  Enabled: false

Rails/IndexBy:
  Enabled: false

Rails/UniqueValidationWithoutIndex:
  Enabled: false

Migration/DepartmentName:
  Enabled: false

Lint/RedundantCopDisableDirective:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Layout/BeginEndAlignment:
  Enabled: false

Lint/BinaryOperatorWithIdenticalOperands:
  Enabled: false

Lint/ConstantDefinitionInBlock:
  Enabled: false

Lint/DuplicateRequire:
  Enabled: false

Lint/DuplicateRescueException:
  Enabled: false

Lint/EmptyConditionalBody:
  Enabled: false

Lint/EmptyFile:
  Enabled: false

Lint/FloatComparison:
  Enabled: false

Lint/IdentityComparison:
  Enabled: false

Lint/MissingSuper:
  Enabled: false

Lint/OutOfRangeRegexpRef:
  Enabled: false

Lint/SelfAssignment:
  Enabled: false

Lint/TopLevelReturnWithArgument:
  Enabled: false

Lint/TrailingCommaInAttributeDeclaration:
  Enabled: false

Lint/UnreachableLoop:
  Enabled: false

Lint/UselessMethodDefinition:
  Enabled: false

Lint/UselessTimes:
  Enabled: false

Style/CombinableLoops:
  Enabled: false

Style/ExplicitBlockArgument:
  Enabled: false

Style/GlobalStdStream:
  Enabled: false

Style/KeywordParametersOrder:
  Enabled: false

Style/OptionalBooleanParameter:
  Enabled: false

Style/RedundantSelfAssignment:
  Enabled: false

Style/SingleArgumentDig:
  Enabled: false

Style/SoleNestedConditional:
  Enabled: false

Style/StringConcatenation:
  Enabled: false

Rails/AfterCommitOverride:
  Enabled: false

Rails/SquishedSQLHeredocs:
  Enabled: false

Rails/WhereNot:
  Enabled: false

Performance/Sum:
  Enabled: false
