version: "3.0"
services:
  web:
    container_name: "web-app"
    hostname: "web-app"
    build:
      context: .
      dockerfile: "docker/web/Dockerfile"
    tty: true
    ports:
      - "3100:3100"
    volumes:
      - .:/app-server
      - gem_cache:/usr/local/bundle/gems
      - node_modules:/app-server/node_modules
    depends_on:
      - mysql
  mysql:
    container_name: "mysql-app"
    hostname: "mysql-app"
    build:
      context: .
      dockerfile: "docker/mysql/Dockerfile"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: root
    volumes:
      - db_data:/var/lib/mysql
  nginx:
    container_name: "nginx"
    hostname: "nginx"
    build:
      context: .
      dockerfile: "docker/nginx/Dockerfile"
    ports:
      - "90:80"
    depends_on:
      - web
volumes:
  gem_cache:
  db_data:
  node_modules:
